package Paquete;
// Generated Mar 7, 2016 4:51:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombre;
     private String appat;
     private String apmat;
     private Date fechanac;
     private String email;

    public Usuario() {
    }

	
    public Usuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Usuario(int idusuario, String nombre, String appat, String apmat, Date fechanac, String email) {
       this.idusuario = idusuario;
       this.nombre = nombre;
       this.appat = appat;
       this.apmat = apmat;
       this.fechanac = fechanac;
       this.email = email;
    }
   
     @Id 

    
    @Column(name="idusuario", unique=true, nullable=false)
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }

    
    @Column(name="nombre", length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="appat", length=25)
    public String getAppat() {
        return this.appat;
    }
    
    public void setAppat(String appat) {
        this.appat = appat;
    }

    
    @Column(name="apmat", length=25)
    public String getApmat() {
        return this.apmat;
    }
    
    public void setApmat(String apmat) {
        this.apmat = apmat;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechanac", length=13)
    public Date getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(Date fechanac) {
        this.fechanac = fechanac;
    }

    
    @Column(name="email", length=40)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


